@echo off
rem Screenium installer for Windows.
rem
rem Installs the `screenium` command into %USERPROFILE%\.local\bin (and adds
rem it to PATH if needed), and sets up the project environment with uv. Run
rem this from a fresh clone of the repository.
rem
rem Usage:
rem   git clone https://github.com/samTheComputerArchitect/Screenium.git
rem   cd Screenium
rem   install.bat
setlocal enabledelayedexpansion

set "INSTALL_DIR=%USERPROFILE%\.local\bin"
set "PROJECT_DIR=%~dp0"
if "%PROJECT_DIR:~-1%"=="\" set "PROJECT_DIR=%PROJECT_DIR:~0,-1%"

echo ==^> Screenium installer
echo ==^> Project directory: %PROJECT_DIR%

rem 1. Make sure uv is available.
where uv >nul 2>nul
if errorlevel 1 (
    echo ==^> uv not found; installing via winget...
    winget install --id=astral-sh.uv -e --accept-source-agreements --accept-package-agreements
    rem Refresh PATH for the current session.
    set "PATH=%USERPROFILE%\.local\bin;%PATH%"
)
where uv >nul 2>nul
if errorlevel 1 (
    echo error: uv could not be found. Install it manually and re-run. >&2
    exit /b 1
)
echo     using uv: %USERPROFILE%\.local\bin\uv

rem 2. Set up the project environment (creates .venv and installs deps).
echo ==^> Setting up project environment with uv
uv --directory "%PROJECT_DIR%" sync
if errorlevel 1 exit /b 1
echo     environment ready

rem 3. Install the `screenium` command into the bin directory.
echo ==^> Installing 'screenium' command into %INSTALL_DIR%
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"

rem Write a launcher that references this project directory so it stays valid.
> "%INSTALL_DIR%\screenium.cmd" (
    echo @echo off
    echo rem Generated by install.bat - do not edit.
    echo uv --directory "%PROJECT_DIR%" run python screenrecorder.py %%*
    echo exit /b %%ERRORLEVEL%%
)

rem 4. Make sure the bin directory is on PATH (per-user PATH registry).
set "REG_KEY=HKCU\Environment"
for /f "skip=2 tokens=2*" %%A in ('reg query "%REG_KEY%" /v Path 2^>nul') do set "USER_PATH=%%B"
echo %USER_PATH% | findstr /i "%INSTALL_DIR%" >nul 2>nul
if errorlevel 1 (
    echo     NOT on PATH; adding to user PATH...
    if defined USER_PATH (
        setx PATH "%INSTALL_DIR%;%USER_PATH%"
    ) else (
        setx PATH "%INSTALL_DIR%"
    )
    echo     added. Open a NEW terminal before running screenium.
) else (
    echo     already on PATH.
)

echo.
echo ==^> Done! Open a new terminal and run 'screenium' to start recording.
endlocal
